### ISSUE TITLE
Small Maintenance Updates

### ISSUE THREAD

**Issue by anthonygclark** [jaysh/eztvit-python#3]
http://paste.debian.net/plain/758243

I don't feel like making a pull request for such a small diff. Above is a link to a diff that adds only a few minor things, it will expire in 90 days:

* It fixes the dropdown `<select>` match to 'q2'
* It adds `lxml` as a second arg to BeautifulSoup calls reduce the complaining from BS
* Adds partial show name matching via `str.find` since it's hard to guess if the show is going to be camelcase or have a year after it, i.e., "MythBusters (2003)"

Please feel free to use or distribute this patch under the same license as the project, whatever that may be.

**Comment by jaysh** [comment]
Thanks a bunch for these. I've incorporated the changes into the codebase and performed a release on PyPi.
